site_name: Notes of Phaser 3
pages:
- Home: index.md
- System:
    - Game: game.md
    - Scene manager: scenemanager.md
    - Scene: scene.md
    - Snapshot: snapshot.md
- Loader:
    - Loader: loader.md
    - Webfont loader: webfontloader.md
    - Await loader:  awaitloader.md
- Game object:
    - Game object: gameobject.md
    - Sprite:
        - Single image:
            - Image: image.md
            - Sprite: sprite.md
            - Quad: quad.md    
        - Multiple images: 
            - Blitter: blitter.md
            - Particles: particles.md        
            - Tile sprite: tilesprite.md
        - Texture: texture.md
    - Text:
        - Canvas text:
            - Text: text.md
            - BBCode Text: bbcodetext.md
            - Tag Text: tagtext.md
        - Bitmap text:
            - Static bitmap text: bitmaptext.md
            - Dynamic bitmap text: dynamicbitmaptext.md
        - Behaviors:
            - Typing: texttyping.md    
            - Page: textpage.md
    - Graphics:
        - Graphics: graphics.md
        - Canvas: canvas.md
        - Render texture: rendertexture.md
    - Tile map:
        - Tile map: tilemap.md
    - Container:
        - Container: container.md
        - Container Lite: containerlite.md
        - Group: group.md
        - Group actions: groupactions.md
        - Grid table: gridtable.md
    - Zone: zone.md
    - DOM element:
        - DOM element: domelement.md
    - Behaviors:
        - Move to: moveto.md
        - Fade out destroy: fadeoutdestroy.md
        - Path follower: pathfollower.md
        - Arcade:
            - Physics: arcade.md        
    - Display:
        - Mask: mask.md
- Input:
    - Input: input.md
    - Touch:    
        - Touch events: touchevents.md
        - Cursor: cursor.md
        - Drag: drag.md
        - Slider: slider.md
        - Virtual joystick: virtualjoystick.md
    - Keyboard:
        - Keyboard events: keyboardevents.md
- Audio:
    - Audio: audio.md
    - Volume fading: fadevolume.md
- Camera:
    - Camera: camera.md
    - Filters:
        - Swirl: swirlpipeline.md
        - Pixelation: pixelationpipeline.md
- Logic:
    - Event emitter: eventemitter3.md
    - Run commands:
      - Run commands: runcommands.md
      - Sequence: sequence.md
      - CSV scenario: csvscenario.md
      - TCRP:
          - Recoder: tcrprecoderplugin.md
          - Player: tcrpplayerplugin.md
    - FSM: fsm.md
- Data:
    - Data manager: datamanager.md
    - Array: array.md
    - CSV:
        - CSV to array: csvtoarray.md
        - CSV to hash table: csvtohashtable.md
    - Database:
        - LokiJs: lokijs.md
- Math:
    - Tween: tween.md
    - Distance: distance.md
    - Angle: angle.md
    - Random:
        - Random number: random.md
        - Gashapon: gashapon.md
    - Color: color.md  
    - Geometry:
        - Circle: geom-circle.md
        - Rectangle: geom-rectangle.md
        - Line: geom-line.md
        - Point: geom-point.md
    - Path: path.md
- String:
    - Format:
        - Format: format.md
        - Mustache: mustache.md
    - Pad: pad.md
    - Capitalizes first: capitalizes-first.md
    - Reverse: reverse-string.md
    - LZ string: lzstring.md
    - XOR: xor.md
    - UUID: uuid.md
- Time:
    - Date: date.md
    - Timer: timer.md
    - Timeline: timeline.md    
    - Clock: clock.md
- Storage:
    - Offline:
        - Key-value pairs:
            - LocalStorage: localstorage.md
            - LocalForage: localforage.md
    - Online:
        - Firebase:
            - Authentication: firebase-auth.md
            - Firestore: firebase-firestore.md
            - Storage: firebase-storage.md


extra_javascript:
- js/mermaid/mermaid.min.js
- js/umlconvert.js 

theme:
    name: 'material'
    logo: 'images/logo.svg'
    palette:
        primary: 'blue'
        accent: 'blue'

site_author: rexrainbow
site_url: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/index.html

extra:
    social:
        - type: github
          link: https://github.com/rexrainbow/
    disqus: 'notes-of-phaser3'

google_analytics:
    - 'UA-119804412-1'
    - 'auto'      

use_directory_urls: false
    
markdown_extensions:
- admonition
- codehilite(guess_lang=false,linenums=false)
- toc(permalink=true)
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences: [
       {name: mermaid, class: mermaid}
    ]
- pymdownx.tasklist
- pymdownx.tilde